begin;

insert into auth.users(id,instance_id,aud,role,is_anonymous,raw_app_meta_data,created_at,updated_at) values
('91000000-0000-4000-8000-000000000001','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{"provider":"apple","providers":["apple"]}',now(),now()),
('91000000-0000-4000-8000-000000000002','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{"provider":"apple","providers":["apple"]}',now(),now()),
('91000000-0000-4000-8000-000000000003','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{"provider":"apple","providers":["apple"]}',now(),now()),
('91000000-0000-4000-8000-000000000004','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{}',now(),now()),
('91000000-0000-4000-8000-000000000005','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{"provider":"apple","providers":["apple"]}',now(),now()),
('91000000-0000-4000-8000-000000000006','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{"provider":"apple","providers":["apple"]}',now(),now()),
('91000000-0000-4000-8000-000000000007','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{"provider":"apple","providers":["apple"]}',now(),now()),
('91000000-0000-4000-8000-000000000008','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{"provider":"apple","providers":["apple"]}',now(),now()),
('91000000-0000-4000-8000-000000000009','00000000-0000-0000-0000-000000000000','authenticated','authenticated',false,'{"provider":"apple","providers":["apple"]}',now(),now());

do $$
declare host_id uuid:='91000000-0000-4000-8000-000000000001'; member_id uuid:='91000000-0000-4000-8000-000000000002'; member_account uuid:='91000000-0000-4000-8000-000000000002'; outsider_id uuid:='91000000-0000-4000-8000-000000000003'; unlinked_id uuid:='91000000-0000-4000-8000-000000000004'; joiner_id uuid:='91000000-0000-4000-8000-000000000005'; pid uuid; create_result jsonb; redeem_result jsonb; agreement jsonb; rejoined_agreement jsonb; epoch uuid; rejoined_epoch uuid; state jsonb; i int; cutoff_sleep date; cutoff_activity date; source uuid:='93000000-0000-4000-8000-000000000001'; fresh_source uuid:='93000000-0000-4000-8000-000000000014'; member_membership uuid; pending_round uuid; ledger uuid; migrated_source uuid:='93000000-0000-4000-8000-000000000007'; legacy_source uuid:='93000000-0000-4000-8000-000000000010'; legacy_all_source uuid:='93000000-0000-4000-8000-000000000011'; retained_pid uuid; retained_agreement jsonb; account_pid uuid; account_agreement jsonb;
begin
  create_result:=public.night_flock_v4_command(host_id,jsonb_build_object('command','createParty','name','Archive','timeZoneIdentifier','UTC','idempotencyKey',repeat('a',64)));
  pid:=(create_result->>'resolvedPartyID')::uuid;
  if pid is null or (public.night_flock_v4_command(host_id,jsonb_build_object('command','createParty','name','Archive','timeZoneIdentifier','UTC','idempotencyKey',repeat('a',64)))->>'resolvedPartyID')::uuid<>pid then raise exception 'createParty did not return/replay command-bound party'; end if;
  insert into private.night_flock_v4_memberships(party_id,user_id,role) values(pid,member_id,'member');
  begin
    perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',gen_random_uuid(),'memberEpochID',gen_random_uuid(),'sourceID',gen_random_uuid(),'revision',1,'kind','sleep','localDate','2026-08-29','timeZoneIdentifier','UTC','minutes',420,'evidence','none'));
    raise exception 'publication without agreement accepted';
  exception when raise_exception then if sqlerrm<>'current_membership_required' then raise; end if; end;
  agreement:=public.night_flock_v4_command(member_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',pid,'agreementVersion',1,'timeZoneIdentifier','UTC'));
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',pid,'agreementVersion',1,'timeZoneIdentifier','UTC'));
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','startRound','partyID',pid,'timeZoneIdentifier','UTC'));
  insert into private.night_flock_v4_invites(party_id,lookup_digest,ciphertext,nonce,key_version,created_by) values(pid,extensions.digest('ABCD23456789','sha256'),'\\x00'::bytea,decode(repeat('00',12),'hex'),1,host_id);
  redeem_result:=public.night_flock_v4_command(joiner_id,jsonb_build_object('command','redeemInvite','inviteCode','ABCD23456789','idempotencyKey',repeat('b',64)));
  if (redeem_result->>'resolvedPartyID')::uuid<>pid or (public.night_flock_v4_command(joiner_id,jsonb_build_object('command','redeemInvite','inviteCode','ABCD23456789','idempotencyKey',repeat('b',64)))->>'resolvedPartyID')::uuid<>pid then raise exception 'redeemInvite did not return/replay command-bound party'; end if;
  epoch:=(agreement->>'memberEpochID')::uuid;
  update private.night_flock_v4_shared_habits_agreements set accepted_at='2026-08-28 10:00:00+00',first_eligible_sleep_night='2026-08-30',first_eligible_wind_down_date='2026-08-28',first_eligible_activity_date='2026-08-28' where id=(agreement->>'agreementID')::uuid;
  select id into member_membership from private.night_flock_v4_memberships where party_id=pid and user_id=member_id;
  select id into pending_round from private.night_flock_v4_rounds where party_id=pid order by created_at limit 1;
  -- The migration's bounded legacy activity date belongs to the agreement,
  -- not the PostgreSQL session. This deliberately differs from the UTC
  -- agreement while both source instants remain on 2026-08-27 UTC.
  perform set_config('TimeZone','Asia/Singapore',true);
  insert into private.night_flock_v4_activity_ledger(id,user_id,source_event_id,kind,outcome,started_at,ended_at,wind_down_minutes,phone_away_minutes,status_revision) values(gen_random_uuid(),member_id,migrated_source,'windDown','completed','2026-08-27 19:00+00','2026-08-27 20:00+00',43,0,3) returning id into ledger;
  insert into public.night_flock_v4_party_activities(party_id,round_id,member_id,ledger_id,kind,outcome,activity_day,wind_down_minutes,phone_away_minutes,revision,observed_at) values(pid,pending_round,member_membership,ledger,'windDown','completed',1,43,0,3,'2026-08-27 20:00+00');
  insert into private.night_flock_v4_membership_stream_activities(party_id,member_id,member_epoch_id,source_event_id,kind,outcome,wind_down_minutes,phone_away_minutes,revision,occurred_at) values(pid,member_membership,epoch,migrated_source,'windDown','completed',43,0,4,'2026-08-27 20:01+00');
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','migrateSharedHabits','partyID',pid,'agreementID',agreement->>'agreementID'));
  perform set_config('TimeZone','UTC',true);
  if (select count(*) from private.night_flock_v4_shared_habits_records r where r.party_id=pid and r.author_user_id=member_account and r.source_id=migrated_source and r.kind='windDown')<>1 then raise exception 'round and stream migration was not cross-source deduplicated'; end if;
  if exists(select 1 from private.night_flock_v4_shared_habits_records r where r.party_id=pid and r.source_id=migrated_source and r.local_date is not null) then raise exception 'migration invented a nightly anchor'; end if;
  if (select r.activity_date from private.night_flock_v4_shared_habits_records r where r.party_id=pid and r.author_user_id=member_account and r.source_id=migrated_source and r.kind='windDown')<>date '2026-08-27' then raise exception 'migration activity date followed the session timezone instead of the agreement'; end if;
  select first_eligible_sleep_night,first_eligible_activity_date into cutoff_sleep,cutoff_activity from private.night_flock_v4_shared_habits_agreements where id=(agreement->>'agreementID')::uuid;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID',source,'revision',1,'kind','windDown','localDate','2026-08-27','timeZoneIdentifier','Asia/Singapore','minutes',10,'evidence','none')); raise exception 'pre-agreement wind down accepted'; exception when raise_exception then if sqlerrm<>'publication_before_agreement' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID',source,'revision',1,'kind','windDown','localDate','2026-08-29','timeZoneIdentifier','Asia/Singapore','minutes',10,'evidence','none'));
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','93000000-0000-4000-8000-000000000002','revision',1,'kind','phoneAway','localDate','2026-08-27','timeZoneIdentifier','Asia/Singapore','minutes',10,'evidence','none')); raise exception 'pre-agreement PA accepted'; exception when raise_exception then if sqlerrm<>'publication_before_agreement' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','93000000-0000-4000-8000-000000000002','revision',1,'kind','phoneAway','localDate',(now() at time zone 'UTC')::date::text,'timeZoneIdentifier','UTC','minutes',10,'evidence','none'));
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','93000000-0000-4000-8000-000000000003','revision',1,'kind','sleep','localDate','2026-08-29','timeZoneIdentifier','UTC','minutes',420,'evidence','none')); raise exception 'partial sleep window accepted'; exception when raise_exception then if sqlerrm<>'publication_before_agreement' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','93000000-0000-4000-8000-000000000003','revision',1,'kind','sleep','localDate','2026-08-30','timeZoneIdentifier','UTC','minutes',420,'evidence','none'));
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','93000000-0000-4000-8000-000000000015','revision',1,'kind','sleep','localDate','2026-08-30','timeZoneIdentifier','Asia/Singapore','minutes',420,'evidence','none')); raise exception 'sleep accepted under a different agreement time zone'; exception when raise_exception then if sqlerrm<>'agreement_timezone_mismatch' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','93000000-0000-4000-8000-000000000008','revision',1,'kind','sleep','localDate','2026-08-30','timeZoneIdentifier','UTC','minutes',780,'evidence','none'));
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','93000000-0000-4000-8000-000000000009','revision',1,'kind','sleep','localDate','2026-08-30','timeZoneIdentifier','UTC','minutes',1501,'evidence','none')); raise exception 'sleep over 25 hours accepted'; exception when check_violation then null; end;
  for i in 1..105 loop
    -- Keep the aggregate and its pagination fillers on the contributor's
    -- agreement-local current day. This agreement is UTC, so a Singapore
    -- midnight does not move the fixture outside its period basis.
    perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID',('92000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'revision',1780000000000+i,'kind','phoneAway','localDate',(now() at time zone 'UTC')::date::text,'timeZoneIdentifier','UTC','minutes',30,'outcome','completed','evidence','none'));
  end loop;
  state:=public.night_flock_v4_state(host_id,'habits',pid,null);
  if jsonb_array_length(state->'records')<>100 or state->>'nextCursor' is null then raise exception 'archive pagination did not page 105 records'; end if;
  if jsonb_array_length(state->'periods')<>9 then raise exception 'full-dataset per-member-kind periods were not returned'; end if;
  if (select (value->>'coveredNights')::int from jsonb_array_elements(state->'periods') value where (value->>'memberID')::uuid=member_membership and value->>'kind'='phoneAway' and value->>'period'='lastNight')<>1
     or abs((select (value->>'averageMinutes')::numeric from jsonb_array_elements(state->'periods') value where (value->>'memberID')::uuid=member_membership and value->>'kind'='phoneAway' and value->>'period'='lastNight')-3160)>0.001 then raise exception 'period aggregation used the first page instead of the full dataset'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','92000000-0000-4000-8000-000000000001','revision',1780000000001,'kind','phoneAway','localDate',(now() at time zone 'UTC')::date::text,'timeZoneIdentifier','UTC','minutes',30,'outcome','completed','evidence','none'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID','92000000-0000-4000-8000-000000000001','revision',1,'kind','phoneAway','localDate',(now() at time zone 'UTC')::date::text,'timeZoneIdentifier','UTC','minutes',30,'outcome','completed','evidence','none'));
  if (select revision::text from private.night_flock_v4_parties where id=pid)<>state->>'snapshotRevision' or jsonb_array_length((public.night_flock_v4_state(host_id,'habits',pid,state->>'nextCursor'))->'records')<>10 then raise exception 'idempotent/older publication churned the archive cursor'; end if;
  if jsonb_array_length((public.night_flock_v4_state(host_id,'habits',pid,state->>'nextCursor'))->'records')<>10 then raise exception 'composite cursor did not return remaining records'; end if;
  if state#>>'{records,0,sourceID}' is not null then raise exception 'peer source identity leaked'; end if;
  state:=public.night_flock_v4_state(member_id,'habits',pid,null);
  if state#>>'{records,0,sourceID}' is null then raise exception 'owner source identity missing'; end if;
  insert into public.night_flock_blocks(blocker_user_id,blocked_user_id) values(host_id,member_id);
  if jsonb_array_length((public.night_flock_v4_state(host_id,'habits',pid,null))->'records')<>0 then raise exception 'blocked former/current author leaked archive'; end if;
  delete from public.night_flock_blocks where blocker_user_id=host_id and blocked_user_id=member_id;
  begin perform public.night_flock_v4_state(outsider_id,'habits',pid,null); raise exception 'outsider read archive'; exception when raise_exception then if sqlerrm<>'current_membership_required' then raise; end if; end;
  begin perform public.night_flock_v4_state(unlinked_id,'habits',pid,null); raise exception 'unlinked reader accepted'; exception when raise_exception then if sqlerrm<>'Apple-linked account required' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID',source,'revision',2,'kind','phoneAway','localDate',cutoff_activity::text,'timeZoneIdentifier','UTC','minutes',20,'evidence','none'));
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',agreement->>'agreementID','memberEpochID',epoch,'sourceID',source,'revision',2,'kind','phoneAway','localDate',cutoff_activity::text,'timeZoneIdentifier','Asia/Singapore','minutes',20,'evidence','none')); raise exception 'equal revision different zone accepted'; exception when raise_exception then if sqlerrm<>'stale_revision' then raise; end if; end;
  -- A source tombstone must remove both legacy/public and membership/private projections,
  -- then suppress replay while retaining the independent reward authority ledger.
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sourceEventID',legacy_source,'status','phoneAwayActive','revision',3,'observedAt',now()-interval '5 minutes'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID',legacy_source,'status','phoneAwayActive','revision',4,'observedAt',now()+interval '2 minutes'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sourceEventID',legacy_source,'kind','phoneAway','outcome','completed','startedAt',now()-interval '20 minutes','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',1));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sharingScope','membership','sourceEventID',legacy_source,'kind','phoneAway','outcome','completed','startedAt',now()-interval '20 minutes','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',2));
  if not exists(select 1 from public.night_flock_v4_party_activities x join private.night_flock_v4_activity_ledger l on l.id=x.ledger_id where x.party_id=pid and l.user_id=member_account and l.source_event_id=legacy_source)
     or not exists(select 1 from private.night_flock_v4_membership_stream_activities x where x.party_id=pid and x.source_event_id=legacy_source)
     or not exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.member_id=member_membership)
     or not exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id=legacy_source) then raise exception 'pre-delete legacy or membership projection was not created'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','deleteSharedHabitHistory','partyID',pid,'sourceID',legacy_source));
  if exists(select 1 from public.night_flock_v4_party_activities x join private.night_flock_v4_activity_ledger l on l.id=x.ledger_id where x.party_id=pid and l.user_id=member_account and l.source_event_id=legacy_source)
     or exists(select 1 from private.night_flock_v4_membership_stream_activities x where x.party_id=pid and x.source_event_id=legacy_source)
     or exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.member_id=member_membership)
     or exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id=legacy_source) then raise exception 'source deletion left a visible projection'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sourceEventID',legacy_source,'kind','phoneAway','outcome','completed','startedAt',now()-interval '20 minutes','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',5));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sharingScope','membership','sourceEventID',legacy_source,'kind','phoneAway','outcome','completed','startedAt',now()-interval '20 minutes','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',6));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sourceEventID',legacy_source,'status','phoneAwayActive','revision',7,'observedAt',now()-interval '3 minutes'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID',legacy_source,'status','phoneAwayActive','revision',8,'observedAt',now()+interval '3 minutes'));
  if exists(select 1 from public.night_flock_v4_party_activities x join private.night_flock_v4_activity_ledger l on l.id=x.ledger_id where x.party_id=pid and l.user_id=member_account and l.source_event_id=legacy_source)
     or exists(select 1 from private.night_flock_v4_membership_stream_activities x where x.party_id=pid and x.source_event_id=legacy_source)
     or exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.member_id=member_membership)
     or exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id=legacy_source)
     or not exists(select 1 from private.night_flock_v4_activity_ledger l where l.user_id=member_account and l.source_event_id=legacy_source) then raise exception 'source tombstone replay leaked a projection or erased reward authority'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sourceEventID',legacy_all_source,'status','phoneAwayActive','revision',3,'observedAt',now()-interval '5 minutes'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID',legacy_all_source,'status','phoneAwayActive','revision',4,'observedAt',now()+interval '2 minutes'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sourceEventID',legacy_all_source,'kind','phoneAway','outcome','completed','startedAt',now()-interval '20 minutes','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',1));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sharingScope','membership','sourceEventID',legacy_all_source,'kind','phoneAway','outcome','completed','startedAt',now()-interval '20 minutes','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',2));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','deleteSharedHabitHistory','partyID',pid,'allSources',true));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sourceEventID',legacy_all_source,'kind','phoneAway','outcome','completed','startedAt',now()-interval '20 minutes','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',5));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sharingScope','membership','sourceEventID',legacy_all_source,'kind','phoneAway','outcome','completed','startedAt',now()-interval '20 minutes','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',6));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sourceEventID',legacy_all_source,'status','phoneAwayActive','revision',7,'observedAt',now()-interval '3 minutes'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID',legacy_all_source,'status','phoneAwayActive','revision',8,'observedAt',now()+interval '3 minutes'));
  if exists(select 1 from public.night_flock_v4_party_activities x join private.night_flock_v4_activity_ledger l on l.id=x.ledger_id where x.party_id=pid and l.user_id=member_account and l.source_event_id=legacy_all_source)
     or exists(select 1 from private.night_flock_v4_membership_stream_activities x where x.party_id=pid and x.source_event_id=legacy_all_source)
     or exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.member_id=member_membership)
     or exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id=legacy_all_source)
     or not exists(select 1 from private.night_flock_v4_activity_ledger l where l.user_id=member_account and l.source_event_id=legacy_all_source)
     or not exists(select 1 from private.night_flock_v4_grants g join private.night_flock_v4_activity_ledger l on l.id=g.ledger_id where g.party_id=pid and l.user_id=member_account and l.source_event_id=legacy_all_source) then raise exception 'all-sources tombstone replay leaked a projection or erased an earned grant'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','leaveParty','partyID',pid));
  -- Rejoin in the same transaction: the new agreement permits only new source
  -- IDs; all old all-sources snapshots remain individually tombstoned.
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','redeemInvite','inviteCode','ABCD23456789'));
  rejoined_agreement:=public.night_flock_v4_command(member_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',pid,'agreementVersion',1,'timeZoneIdentifier','Asia/Singapore'));
  rejoined_epoch:=(rejoined_agreement->>'memberEpochID')::uuid;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',rejoined_agreement->>'agreementID','memberEpochID',rejoined_epoch,'sourceID',legacy_all_source,'revision',9,'kind','phoneAway','localDate',(now() at time zone 'Asia/Singapore')::date::text,'timeZoneIdentifier','Asia/Singapore','minutes',10,'evidence','none')); raise exception 'old source escaped all-sources fence after rejoin'; exception when raise_exception then if sqlerrm<>'shared_history_deleted' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',rejoined_agreement->>'agreementID','memberEpochID',rejoined_epoch,'sourceID',fresh_source,'revision',1,'kind','phoneAway','localDate',(now() at time zone 'Asia/Singapore')::date::text,'timeZoneIdentifier','Asia/Singapore','minutes',20,'evidence','none'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sourceEventID',legacy_all_source,'status','phoneAwayActive','revision',10,'observedAt',now()+interval '1 minute'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID',legacy_all_source,'status','phoneAwayActive','revision',11,'observedAt',now()+interval '2 minutes'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sourceEventID',fresh_source,'status','phoneAwayActive','revision',1,'observedAt',now()+interval '3 minutes'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID',fresh_source,'status','phoneAwayActive','revision',2,'observedAt',now()+interval '4 minutes'));
  if not exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.member_id=member_membership and x.source_event_id=fresh_source)
     or not exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id=fresh_source)
     or exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id=legacy_all_source) then raise exception 'old A tombstone suppressed fresh B status or allowed old replay'; end if;
  -- A source that was still local when history is withdrawn has no exact
  -- source tombstone. After leave/delete/rejoin, the all-sources withdrawal
  -- cutoff must still stop that old account-wide V4 source from projecting
  -- into this party, while a genuinely post-rejoin source remains eligible.
  update private.night_flock_v4_rounds set started_at=now()-interval '2 minutes' where party_id=pid and status='active';
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','leaveParty','partyID',pid));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','deleteSharedHabitHistory','partyID',pid,'allSources',true));
  if not exists(select 1 from private.night_flock_v4_shared_habits_tombstones t where t.party_id=pid and t.user_id=member_id and t.all_sources and t.member_epoch_id is null and t.withdrawal_cutoff_at is not null) then raise exception 'post-leave withdrawal did not retain a durable source cutoff'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','redeemInvite','inviteCode','ABCD23456789'));
  -- This source crosses the withdrawal boundary.  Every derived projection
  -- must use its factual start, not its later terminal/status time.
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sharingScope','membership','sourceEventID','93000000-0000-4000-8000-000000000016','kind','phoneAway','outcome','completed','startedAt',now()-interval '1 minute','endedAt',now()+interval '1 minute','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',1));
  if exists(select 1 from public.night_flock_v4_party_activities x join private.night_flock_v4_activity_ledger l on l.id=x.ledger_id where x.party_id=pid and l.user_id=member_account and l.source_event_id='93000000-0000-4000-8000-000000000016'::uuid)
     or exists(select 1 from private.night_flock_v4_membership_stream_activities x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000016'::uuid)
     or exists(select 1 from private.night_flock_v4_grants g join private.night_flock_v4_activity_ledger l on l.id=g.ledger_id where g.party_id=pid and l.user_id=member_account and l.source_event_id='93000000-0000-4000-8000-000000000016'::uuid) then raise exception 'post-withdrawal unseen source projected after rejoin'; end if;
  if not exists(select 1 from private.night_flock_v4_shared_habits_tombstones t where t.party_id=pid and t.user_id=member_id and t.source_id='93000000-0000-4000-8000-000000000016'::uuid and not t.all_sources) then raise exception 'blocked unseen source did not acquire an exact terminal tombstone'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sharingScope','membership','sourceEventID','93000000-0000-4000-8000-000000000016','kind','phoneAway','outcome','completed','startedAt',now()+interval '2 minutes','endedAt',now()+interval '3 minutes','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',2));
  if exists(select 1 from public.night_flock_v4_party_activities x join private.night_flock_v4_activity_ledger l on l.id=x.ledger_id where x.party_id=pid and l.user_id=member_account and l.source_event_id='93000000-0000-4000-8000-000000000016'::uuid)
     or exists(select 1 from private.night_flock_v4_membership_stream_activities x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000016'::uuid)
     or exists(select 1 from private.night_flock_v4_grants g join private.night_flock_v4_activity_ledger l on l.id=g.ledger_id where g.party_id=pid and l.user_id=member_account and l.source_event_id='93000000-0000-4000-8000-000000000016'::uuid) then raise exception 'exact withdrawal tombstone allowed a higher-revision moved-time replay'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishActivity','sharingScope','membership','sourceEventID','93000000-0000-4000-8000-000000000017','kind','phoneAway','outcome','completed','startedAt',now()+interval '1 second','endedAt',now()+interval '2 seconds','windDownMinutes',0,'phoneAwayMinutes',10,'statusRevision',1));
  if not exists(select 1 from public.night_flock_v4_party_activities x join private.night_flock_v4_activity_ledger l on l.id=x.ledger_id where x.party_id=pid and l.user_id=member_account and l.source_event_id='93000000-0000-4000-8000-000000000017'::uuid)
     or not exists(select 1 from private.night_flock_v4_membership_stream_activities x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000017'::uuid)
     or not exists(select 1 from private.night_flock_v4_grants g join private.night_flock_v4_activity_ledger l on l.id=g.ledger_id where g.party_id=pid and l.user_id=member_account and l.source_event_id='93000000-0000-4000-8000-000000000017'::uuid) then raise exception 'post-rejoin source was suppressed by a prior withdrawal cutoff'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID','93000000-0000-4000-8000-000000000018','status','phoneAwayActive','revision',1,'observedAt',now()-interval '1 minute'));
  if exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000018'::uuid)
     or exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000018'::uuid) then raise exception 'post-withdrawal unseen status projected after rejoin'; end if;
  if not exists(select 1 from private.night_flock_v4_shared_habits_tombstones t where t.party_id=pid and t.user_id=member_id and t.source_id='93000000-0000-4000-8000-000000000018'::uuid and not t.all_sources) then raise exception 'blocked unseen status did not acquire an exact terminal tombstone'; end if;
  -- Exercise the legacy (unscoped) status path as well: a moved post-cutoff
  -- terminal update for the same source cannot revive either projection.
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sourceEventID','93000000-0000-4000-8000-000000000018','status','phoneAwayCompleted','revision',2,'observedAt',now()+interval '2 minutes'));
  if exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000018'::uuid)
     or exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000018'::uuid) then raise exception 'exact status tombstone allowed a higher-revision moved-time replay'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID','93000000-0000-4000-8000-000000000019','status','phoneAwayActive','revision',1,'observedAt',now()+interval '1 minute'));
  if not exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000019'::uuid)
     or not exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000019'::uuid) then raise exception 'post-rejoin status was suppressed by a prior withdrawal cutoff'; end if;
  -- A has an exact tombstone.  Reusing B's otherwise identical public-status
  -- metadata must neither relabel nor delete B after the source is atomic.
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishStatus','sharingScope','membership','sourceEventID','93000000-0000-4000-8000-000000000018','status','phoneAwayActive','revision',1,'observedAt',now()+interval '1 minute'));
  if not exists(select 1 from public.night_flock_v4_statuses x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000019'::uuid and x.status='phoneAwayActive' and x.revision=1 and x.observed_at=now()+interval '1 minute')
     or not exists(select 1 from private.night_flock_v4_membership_stream_statuses x where x.party_id=pid and x.source_event_id='93000000-0000-4000-8000-000000000019'::uuid and x.status='phoneAwayActive' and x.revision=1 and x.observed_at=now()+interval '1 minute') then raise exception 'blocked status replay relabelled or deleted a metadata-colliding fresh source'; end if;
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','createParty','name','Former archive','timeZoneIdentifier','UTC'));
  select id into retained_pid from private.night_flock_v4_parties where host_user_id=host_id and name='Former archive';
  insert into private.night_flock_v4_memberships(party_id,user_id,role) values(retained_pid,member_id,'member');
  retained_agreement:=public.night_flock_v4_command(member_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',retained_pid,'agreementVersion',1,'timeZoneIdentifier','UTC'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedHabit','partyID',retained_pid,'agreementID',retained_agreement->>'agreementID','memberEpochID',retained_agreement->>'memberEpochID','sourceID','93000000-0000-4000-8000-000000000013','revision',1,'kind','phoneAway','localDate',(now() at time zone 'UTC')::date::text,'timeZoneIdentifier','UTC','minutes',10,'evidence','none'));
  if jsonb_array_length((public.night_flock_v4_state(member_id,'list',null,null))->'retainedSharedHabitParties')<>0 then raise exception 'current member received former-history deletion metadata'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','leaveParty','partyID',retained_pid));
  state:=public.night_flock_v4_state(member_id,'list',null,null);
  if jsonb_array_length(state->'retainedSharedHabitParties')<>1 or (state#>>'{retainedSharedHabitParties,0,partyID}')::uuid<>retained_pid or (state#>>'{retainedSharedHabitParties,0,recordCount}')::int<>1 then raise exception 'former member could not discover retained own history'; end if;
  if jsonb_array_length((public.night_flock_v4_state(outsider_id,'list',null,null))->'retainedSharedHabitParties')<>0 then raise exception 'unrelated caller saw retained history'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','deleteSharedHabitHistory','partyID',retained_pid,'allSources',true));
  if jsonb_array_length((public.night_flock_v4_state(member_id,'list',null,null))->'retainedSharedHabitParties')<>0 then raise exception 'deleted retained history remained listed'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','leaveParty','partyID',pid));
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','deleteParty','partyID',pid));
  if exists(select 1 from private.night_flock_v4_shared_habits_records r where r.party_id=pid) or exists(select 1 from private.night_flock_v4_shared_habits_agreements a where a.party_id=pid) then raise exception 'dissolved party retained archive or agreements'; end if;
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','deleteParty','partyID',retained_pid));
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','createParty','name','Account archive','timeZoneIdentifier','UTC'));
  select id into account_pid from private.night_flock_v4_parties where host_user_id=host_id and name='Account archive';
  account_agreement:=public.night_flock_v4_command(host_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',account_pid,'agreementVersion',1,'timeZoneIdentifier','UTC'));
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','publishSharedHabit','partyID',account_pid,'agreementID',account_agreement->>'agreementID','memberEpochID',account_agreement->>'memberEpochID','sourceID','93000000-0000-4000-8000-000000000012','revision',1,'kind','phoneAway','localDate',(now() at time zone 'UTC')::date::text,'timeZoneIdentifier','UTC','minutes',10,'evidence','none'));
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','deleteAccount'));
  if exists(select 1 from private.night_flock_v4_shared_habits_records r where r.author_user_id=host_id)
     or exists(select 1 from private.night_flock_v4_shared_habits_agreements a where a.user_id=host_id) then raise exception 'account deletion retained archive records or agreement receipts'; end if;
end $$;

do $$
declare host_id uuid:='91000000-0000-4000-8000-000000000006'; former_id uuid:='91000000-0000-4000-8000-000000000007'; cascade_id uuid:='91000000-0000-4000-8000-000000000008'; pid uuid; cascade_pid uuid; first_agreement jsonb; second_agreement jsonb; cascade_agreement jsonb; first_epoch uuid; second_epoch uuid; member_id uuid; cursor text; state jsonb; party_revision int; i int;
begin
  pid:=(public.night_flock_v4_command(host_id,jsonb_build_object('command','createParty','name','Epoch basis','timeZoneIdentifier','UTC'))->>'resolvedPartyID')::uuid;
  insert into private.night_flock_v4_memberships(party_id,user_id,role) values(pid,former_id,'member');
  perform public.night_flock_v4_command(host_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',pid,'agreementVersion',1,'timeZoneIdentifier','UTC'));
  first_agreement:=public.night_flock_v4_command(former_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',pid,'agreementVersion',1,'timeZoneIdentifier','UTC'));
  first_epoch:=(first_agreement->>'memberEpochID')::uuid;
  select id into member_id from private.night_flock_v4_memberships where party_id=pid and user_id=former_id;
  for i in 1..101 loop
    perform public.night_flock_v4_command(former_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',first_agreement->>'agreementID','memberEpochID',first_epoch,'sourceID',('94000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'revision',i,'kind','phoneAway','localDate',(now() at time zone 'UTC')::date::text,'timeZoneIdentifier','UTC','minutes',10,'evidence','none'));
  end loop;
  perform public.night_flock_v4_command(former_id,jsonb_build_object('command','leaveParty','partyID',pid));
  update private.night_flock_v4_memberships set status='active',joined_at=now(),left_at=null where id=member_id;
  select id into second_epoch from private.night_flock_v4_membership_epochs where membership_id=member_id and ended_at is null;
  second_agreement:=public.night_flock_v4_command(former_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',pid,'agreementVersion',1,'timeZoneIdentifier','Asia/Singapore'));
  if (second_agreement->>'memberEpochID')::uuid<>second_epoch then raise exception 'rejoin did not issue a new membership epoch'; end if;
  perform public.night_flock_v4_command(former_id,jsonb_build_object('command','publishSharedHabit','partyID',pid,'agreementID',second_agreement->>'agreementID','memberEpochID',second_epoch,'sourceID','94000000-0000-4000-8000-000000000102','revision',1,'kind','phoneAway','localDate',(now() at time zone 'Asia/Singapore')::date::text,'timeZoneIdentifier','Asia/Singapore','minutes',20,'evidence','none'));
  state:=public.night_flock_v4_state(host_id,'habits',pid,null);
  if jsonb_array_length(state->'periods')<>9 then raise exception 'historical agreement time zones duplicated period basis rows'; end if;
  perform public.night_flock_v4_command(former_id,jsonb_build_object('command','leaveParty','partyID',pid));
  state:=public.night_flock_v4_state(host_id,'habits',pid,null); cursor:=state->>'nextCursor';
  if cursor is null then raise exception 'former author fixture did not produce a >100 cursor'; end if;
  select revision into party_revision from private.night_flock_v4_parties where id=pid;
  perform public.night_flock_v4_command(former_id,jsonb_build_object('command','deleteAccount'));
  if (select revision from private.night_flock_v4_parties where id=pid)<=party_revision then raise exception 'former account deletion did not invalidate archive revision'; end if;
  begin perform public.night_flock_v4_state(host_id,'habits',pid,cursor); raise exception 'former account deletion left old cursor valid'; exception when raise_exception then if sqlerrm<>'stale_revision' then raise; end if; end;
  if exists(select 1 from private.night_flock_v4_shared_habits_records where author_user_id=former_id) or exists(select 1 from private.night_flock_v4_shared_habits_agreements where user_id=former_id) then raise exception 'former account deletion retained archive authority'; end if;

  cascade_pid:=(public.night_flock_v4_command(host_id,jsonb_build_object('command','createParty','name','Cascade archive','timeZoneIdentifier','UTC'))->>'resolvedPartyID')::uuid;
  insert into private.night_flock_v4_memberships(party_id,user_id,role) values(cascade_pid,cascade_id,'member');
  cascade_agreement:=public.night_flock_v4_command(cascade_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',cascade_pid,'agreementVersion',1,'timeZoneIdentifier','UTC'));
  perform public.night_flock_v4_command(cascade_id,jsonb_build_object('command','publishSharedHabit','partyID',cascade_pid,'agreementID',cascade_agreement->>'agreementID','memberEpochID',cascade_agreement->>'memberEpochID','sourceID','94000000-0000-4000-8000-000000000103','revision',1,'kind','phoneAway','localDate',(now() at time zone 'UTC')::date::text,'timeZoneIdentifier','UTC','minutes',10,'evidence','none'));
  delete from auth.users where id=cascade_id;
  if exists(select 1 from private.night_flock_v4_shared_habits_records where author_user_id=cascade_id) or exists(select 1 from private.night_flock_v4_shared_habits_agreements where user_id=cascade_id) then raise exception 'auth cascade retained archive records or receipts'; end if;
end $$;

-- V2 social-night integration: this remains a database fixture rather than a
-- Deno mock so membership epochs, tombstones, cursors, and frozen versions
-- exercise the RPC that offline outboxes replay into.
do $$
declare host_id uuid:='91000000-0000-4000-8000-000000000001'; member_id uuid:='91000000-0000-4000-8000-000000000002'; privacy_host_id uuid:='91000000-0000-4000-8000-000000000009'; pid uuid; agreement jsonb; epoch uuid; d date; plan_one uuid:= '95000000-0000-4000-8000-000000000001'; plan_two uuid:= '95000000-0000-4000-8000-000000000002'; midnight_plan uuid:= '95000000-0000-4000-8000-000000000005'; receipt_id uuid:= '95000000-0000-4000-8000-000000000003'; receipt_source uuid:= '95000000-0000-4000-8000-000000000004'; state jsonb; cursor text; i int; plan_id uuid; archive_before int; privacy_pid uuid; privacy_agreement jsonb; privacy_epoch uuid; privacy_plan uuid; privacy_receipt uuid; ordering_pid uuid; ordering_agreement jsonb; ordering_epoch uuid; ordering_plan uuid; freeze_pid uuid; freeze_agreement jsonb; freeze_epoch uuid; freeze_plan uuid;
begin
  -- Every v2 fixture instant below is expressed as a UTC civil timestamp.
  -- Pin the transaction parser explicitly so `date + time` cannot inherit a
  -- developer machine's session zone before the server validates its UTC anchor.
  perform set_config('TimeZone','UTC',true);
  pid:=(public.night_flock_v4_command(host_id,jsonb_build_object('command','createParty','name','V2 archive','timeZoneIdentifier','UTC'))->>'resolvedPartyID')::uuid;
  insert into private.night_flock_v4_memberships(party_id,user_id,role) values(pid,member_id,'member');
  d:=(now() at time zone 'UTC')::date;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_one,'memberEpochID',gen_random_uuid(),'agreementID',gen_random_uuid(),'revision',1,'nightEndingDate',d,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+time '21:30')::timestamptz,'intendedBedtime',(d+time '22:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'v2 publication accepted without agreement'; exception when raise_exception then if sqlerrm<>'publication_before_agreement' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',receipt_id,'memberEpochID',gen_random_uuid(),'agreementID',gen_random_uuid(),'revision',1,'nightEndingDate',d,'timeZoneIdentifier','UTC','outcome','unknown','protectionEvidence','unknown')); raise exception 'v2 receipt accepted without agreement'; exception when raise_exception then if sqlerrm<>'publication_before_agreement' then raise; end if; end;
  agreement:=public.night_flock_v4_command(member_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',pid,'agreementVersion',2,'timeZoneIdentifier','UTC'));
  epoch:=(agreement->>'memberEpochID')::uuid;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','sourceID',gen_random_uuid(),'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(select date_trunc('hour',accepted_at)-interval '5 minutes' from private.night_flock_v4_shared_habits_agreements where id=(agreement->>'agreementID')::uuid),'outcome','partlyCompleted','protectionEvidence','unknown')); raise exception 'pre-consent receipt accepted'; exception when raise_exception then if sqlerrm<>'publication_before_agreement' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','sourceID',gen_random_uuid(),'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','terminalAt',(select date_trunc('hour',accepted_at)-interval '5 minutes' from private.night_flock_v4_shared_habits_agreements where id=(agreement->>'agreementID')::uuid),'outcome','unknown','protectionEvidence','unknown')); raise exception 'pre-consent unknown terminal accepted'; exception when raise_exception then if sqlerrm<>'publication_before_agreement' then raise; end if; end;
  -- The ordinary next-night plans below use ending-date early-morning
  -- anchors, so they remain future at every UTC execution hour. The
  -- pre-consent checks above intentionally ran against the real acceptance
  -- time; pinning this fixture agreement afterward keeps its factual receipt
  -- corrections deterministic without weakening those checks.
  update private.night_flock_v4_shared_habits_agreements set accepted_at=d::timestamptz where id=(agreement->>'agreementID')::uuid;
  if (d+1+time '00:30')::timestamptz <= now() then
    raise exception 'ordinary next-night fixture anchor must remain future';
  end if;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_one,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+8,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+time '21:30')::timestamptz,'intendedBedtime',(d+time '22:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'out-of-window plan accepted'; exception when raise_exception then if sqlerrm<>'publication_outside_plan_window' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_one,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '01:30')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'invalid plan chronology accepted'; exception when raise_exception then if sqlerrm<>'invalid_plan_chronology' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_one,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d,'timeZoneIdentifier','Asia/Singapore','plannedWindDownStart',(d+time '21:30')::timestamptz,'intendedBedtime',(d+time '22:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'timezone mismatch accepted'; exception when raise_exception then if sqlerrm<>'agreement_timezone_mismatch' then raise; end if; end;
  plan_id:=gen_random_uuid();
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_id,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+7,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+6+time '21:30')::timestamptz,'intendedBedtime',(d+6+time '22:00')::timestamptz,'intendedWakeTime',(d+7+time '07:00')::timestamptz,'morningQuietEnd',(d+7+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',pid,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',2,'nightEndingDate',d+7,'timeZoneIdentifier','UTC','cancellationAuthority','privacy'));
  state:=public.night_flock_v4_state(member_id,'sharedNights',pid,null);
  if exists(select 1 from jsonb_array_elements(state->'sharedNightPlans') value where (value->>'planID')::uuid=plan_id) then raise exception 'plan cancellation left the published plan visible'; end if;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',3,'nightEndingDate',d+7,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+6+time '21:30')::timestamptz,'intendedBedtime',(d+6+time '22:00')::timestamptz,'intendedWakeTime',(d+7+time '07:00')::timestamptz,'morningQuietEnd',(d+7+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'plan cancellation allowed a replay'; exception when raise_exception then if sqlerrm<>'shared_night_plan_cancelled' then raise; end if; end;
  plan_id:=gen_random_uuid();
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_id,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+6,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+5+time '21:30')::timestamptz,'intendedBedtime',(d+5+time '22:00')::timestamptz,'intendedWakeTime',(d+6+time '07:00')::timestamptz,'morningQuietEnd',(d+6+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',pid,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',2,'nightEndingDate',d+6,'timeZoneIdentifier','UTC','cancellationAuthority','schedule'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',3,'nightEndingDate',d+6,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+5+time '21:30')::timestamptz,'intendedBedtime',(d+5+time '22:00')::timestamptz,'intendedWakeTime',(d+6+time '07:00')::timestamptz,'morningQuietEnd',(d+6+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+2,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '22:30')::timestamptz,'intendedBedtime',(d+1+time '23:00')::timestamptz,'intendedWakeTime',(d+2+time '23:30')::timestamptz,'morningQuietEnd',(d+3+time '02:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',180,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',date_trunc('hour',now()),'intendedBedtime',date_trunc('hour',now())+interval '30 minutes','intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'first late plan publication accepted'; exception when raise_exception then if sqlerrm<>'shared_night_plan_frozen' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_one,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:30')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',2,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:30:00.100')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'fractional plan timestamp accepted'; exception when raise_exception then if sqlerrm<>'invalid_plan_chronology' then raise; end if; end;
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:30')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb))->>'staleRevision')::boolean,false) then raise exception 'equal revision was not idempotent'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_two,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',2,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:25')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',35,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',midnight_plan,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',3,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:30')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '23:30')::timestamptz,'morningQuietEnd',(d+2+time '02:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',180,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  if not exists(select 1 from private.night_flock_v4_shared_night_plans where id=plan_one and superseded_at is not null) then raise exception 'superseded plan was not retained'; end if;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','outcome','unknown','protectionEvidence','unknown')); raise exception 'missing receipt source accepted'; exception when raise_exception then if sqlerrm<>'invalid_receipt_source' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',receipt_id,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:00')::timestamptz,'outcome','partlyCompleted','windDownMinutes',25,'protectionEvidence','unknown'));
  if not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id and r.plan_id=plan_one and r.plan_revision=1) then raise exception 'frozen receipt did not retain superseded version'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',2,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:05')::timestamptz,'outcome','completed','windDownMinutes',30,'protectionEvidence','unknown'));
  if not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id and r.revision=2 and r.plan_id=plan_one and r.plan_revision=1 and r.outcome='completed') then raise exception 'member-night correction changed frozen plan or did not update factual receipt'; end if;
  archive_before:=(select revision from private.night_flock_v4_parties where id=pid);
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',gen_random_uuid(),'revision',3,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:00')::timestamptz,'outcome','partlyCompleted','windDownMinutes',20,'protectionEvidence','unknown'))->>'staleRevision')::boolean,false) or (select revision from private.night_flock_v4_parties where id=pid)<>archive_before then raise exception 'worse later receipt churned member-night winner'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',gen_random_uuid(),'revision',4,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:10')::timestamptz,'outcome','completed','windDownMinutes',35,'protectionEvidence','unknown'));
  if not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id and r.revision=4 and r.wind_down_minutes=35) then raise exception 'better later receipt did not replace member-night winner'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',5,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:10')::timestamptz,'outcome','completed','windDownMinutes',35,'protectionEvidence','partial'));
  archive_before:=(select revision from private.night_flock_v4_parties where id=pid);
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',6,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:10')::timestamptz,'outcome','completed','windDownMinutes',35,'protectionEvidence','observed'));
  if not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id and r.revision=6 and r.protection_evidence='observed') then raise exception 'partial to observed correction was not retained'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:10')::timestamptz,'outcome','completed','windDownMinutes',36,'protectionEvidence','observed'));
  if not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id and r.wind_down_minutes=36 and r.revision>6) then raise exception 'stronger lower-revision receipt was not transport-promoted'; end if;
  archive_before:=(select revision from private.night_flock_v4_parties where id=pid);
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',8,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:10')::timestamptz,'outcome','completed','windDownMinutes',36,'protectionEvidence','observed','emergencyExitUsed',false));
  if not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id and r.emergency_exit_used=false and r.revision>=8) or (select revision from private.night_flock_v4_parties where id=pid)<>archive_before+1 then raise exception 'known emergency correction did not replace equal-core unknown fact'; end if;
  archive_before:=(select revision from private.night_flock_v4_parties where id=pid);
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',7,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:10')::timestamptz,'outcome','completed','windDownMinutes',36,'protectionEvidence','observed'))->>'staleRevision')::boolean,false) or (select revision from private.night_flock_v4_parties where id=pid)<>archive_before or not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id and r.emergency_exit_used=false) then raise exception 'nil emergency replay erased known fact or churned archive'; end if;
  archive_before:=(select revision from private.night_flock_v4_parties where id=pid);
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',8,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',((d+time '14:35') at time zone 'America/Los_Angeles'),'terminalAt',((d+time '15:10') at time zone 'America/Los_Angeles'),'outcome','completed','windDownMinutes',36,'protectionEvidence','observed','emergencyExitUsed',false))->>'staleRevision')::boolean,false) or (select revision from private.night_flock_v4_parties where id=pid)<>archive_before then raise exception 'equivalent-offset receipt replay churned archive'; end if;
  archive_before:=(select revision from private.night_flock_v4_parties where id=pid);
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',7,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:10')::timestamptz,'outcome','completed','windDownMinutes',35,'protectionEvidence','observed'))->>'staleRevision')::boolean,false) or (select revision from private.night_flock_v4_parties where id=pid)<>archive_before then raise exception 'identical evidence correction churned archive'; end if;
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',8,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:10')::timestamptz,'outcome','completed','windDownMinutes',35,'protectionEvidence','partial'))->>'staleRevision')::boolean,false) or (select revision from private.night_flock_v4_parties where id=pid)<>archive_before then raise exception 'observed evidence degradation churned archive'; end if;
  archive_before:=(select revision from private.night_flock_v4_parties where id=pid);
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',gen_random_uuid(),'revision',2,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','outcome','unknown','protectionEvidence','unknown'))->>'staleRevision')::boolean,false) or (select revision from private.night_flock_v4_parties where id=pid)<>archive_before or not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id and r.source_id=receipt_source) then raise exception 'stale alternate-source correction churned archive or changed provenance'; end if;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','sourceID',gen_random_uuid(),'revision',3,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+2+time '21:35')::timestamptz,'outcome','unknown','protectionEvidence','unknown')); raise exception 'one-sided outside-night actual start accepted'; exception when raise_exception then if sqlerrm<>'invalid_receipt_chronology' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','sourceID',gen_random_uuid(),'revision',3,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','terminalAt',(d+2+time '22:00')::timestamptz,'outcome','unknown','protectionEvidence','unknown')); raise exception 'one-sided outside-night terminal accepted'; exception when raise_exception then if sqlerrm<>'invalid_receipt_chronology' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','deleteSharedHabitHistory','partyID',pid,'sourceID',receipt_source));
  if exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=receipt_id) then raise exception 'source deletion retained v2 receipt'; end if;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','sourceID',gen_random_uuid(),'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','terminalAt',(d+2+time '00:30')::timestamptz,'outcome','unknown','protectionEvidence','unknown')); raise exception 'unbound next-day terminal accepted'; exception when raise_exception then if sqlerrm<>'invalid_receipt_chronology' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',gen_random_uuid(),'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','terminalAt',(d+2+time '00:30')::timestamptz,'outcome','unknown','protectionEvidence','unknown')); raise exception 'mismatched next-day plan terminal accepted'; exception when raise_exception then if sqlerrm<>'invalid_receipt_chronology' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',midnight_plan,'planRevision',3,'sourceID',gen_random_uuid(),'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','terminalAt',(d+2+time '03:00')::timestamptz,'outcome','unknown','protectionEvidence','unknown')); raise exception 'after-plan next-day terminal accepted'; exception when raise_exception then if sqlerrm<>'invalid_receipt_chronology' then raise; end if; end;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',midnight_plan,'planRevision',3,'sourceID',gen_random_uuid(),'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '22:35')::timestamptz,'terminalAt',(d+2+time '00:30')::timestamptz,'outcome','partlyCompleted','windDownMinutes',25,'protectionEvidence','unknown'));
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'planRevision',1,'sourceID',receipt_source,'revision',3,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','outcome','unknown','protectionEvidence','unknown')); raise exception 'source-tombstoned v2 replay accepted'; exception when raise_exception then if sqlerrm<>'shared_history_deleted' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','sourceID',gen_random_uuid(),'revision',3,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35:00.100')::timestamptz,'outcome','unknown','protectionEvidence','unknown')); raise exception 'fractional receipt timestamp accepted'; exception when raise_exception then if sqlerrm<>'invalid_receipt_chronology' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid,'receiptID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','planID',plan_one,'sourceID',gen_random_uuid(),'revision',1,'nightEndingDate',d,'timeZoneIdentifier','UTC','outcome','unknown','protectionEvidence','unknown')); raise exception 'half plan binding accepted'; exception when raise_exception then if sqlerrm<>'invalid_plan_binding' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',3,'nightEndingDate',d,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+time '21:30')::timestamptz,'intendedBedtime',(d+time '22:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb,'bundleID','forbidden')); raise exception 'exact app field accepted'; exception when raise_exception then if sqlerrm<>'invalid_shared_night_payload' then raise; end if; end;
  for i in 3..102 loop
    plan_id:=('95000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid;
    perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',plan_id,'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',i,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:30')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  end loop;
  state:=public.night_flock_v4_state(member_id,'sharedNights',pid,null); cursor:=state->>'sharedNightsNextCursor';
  -- `sharedNights` is a 100-event page. Receipts consume event slots and may
  -- pull their frozen supporting plan into the response, so presentation rows
  -- are between 100 and 200 rather than necessarily 100 plans.
  if cursor is null
    or jsonb_array_length(state->'sharedNightPlans')+jsonb_array_length(state->'sharedNightReceipts')<100
    or jsonb_array_length(state->'sharedNightPlans')+jsonb_array_length(state->'sharedNightReceipts')>200
  then raise exception 'v2 first page was not bounded/cursorized'; end if;
  update private.night_flock_v4_shared_night_plans set planned_wind_down_start=now()-interval '5 minutes' where id=plan_id;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',103,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:30')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'late revision bypassed stored plan freeze'; exception when raise_exception then if sqlerrm<>'shared_night_plan_frozen' then raise; end if; end;
  perform public.night_flock_v4_state(member_id,'sharedNights',pid,cursor);

  -- A plan privacy cancellation is a server-side receipt fence, not merely a
  -- state-projection hide. Keep the already accepted receipt archived, but
  -- reject delayed plan-bound and planless receipts from any source/revision.
  privacy_pid:=(public.night_flock_v4_command(privacy_host_id,jsonb_build_object('command','createParty','name','V2 privacy receipt fence','timeZoneIdentifier','UTC'))->>'resolvedPartyID')::uuid;
  insert into private.night_flock_v4_memberships(party_id,user_id,role) values(privacy_pid,member_id,'member');
  privacy_agreement:=public.night_flock_v4_command(member_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',privacy_pid,'agreementVersion',2,'timeZoneIdentifier','UTC'));
  privacy_epoch:=(privacy_agreement->>'memberEpochID')::uuid;
  update private.night_flock_v4_shared_habits_agreements set accepted_at=d::timestamptz where id=(privacy_agreement->>'agreementID')::uuid;
  privacy_plan:=gen_random_uuid(); privacy_receipt:=gen_random_uuid();
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',privacy_pid,'planID',privacy_plan,'memberEpochID',privacy_epoch,'agreementID',privacy_agreement->>'agreementID','revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:30')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',privacy_pid,'receiptID',privacy_receipt,'memberEpochID',privacy_epoch,'agreementID',privacy_agreement->>'agreementID','planID',privacy_plan,'planRevision',1,'sourceID',gen_random_uuid(),'revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:00')::timestamptz,'outcome','partlyCompleted','windDownMinutes',25,'protectionEvidence','unknown'));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',privacy_pid,'memberEpochID',privacy_epoch,'agreementID',privacy_agreement->>'agreementID','revision',2,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','cancellationAuthority','privacy'));
  select revision into archive_before from private.night_flock_v4_parties where id=privacy_pid;
  if not exists(select 1 from private.night_flock_v4_shared_night_receipts r where r.id=privacy_receipt) then raise exception 'privacy cancellation deleted already archived factual receipt'; end if;
  state:=public.night_flock_v4_state(member_id,'sharedNights',privacy_pid,null);
  if exists(select 1 from jsonb_array_elements(state->'sharedNightReceipts') value where (value->>'receiptID')::uuid=privacy_receipt) then raise exception 'privacy cancellation left historical receipt visible'; end if;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',privacy_pid,'receiptID',gen_random_uuid(),'memberEpochID',privacy_epoch,'agreementID',privacy_agreement->>'agreementID','planID',privacy_plan,'planRevision',1,'sourceID',gen_random_uuid(),'revision',99,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:05')::timestamptz,'outcome','completed','windDownMinutes',30,'protectionEvidence','observed')); raise exception 'privacy-cancelled plan-bound receipt accepted'; exception when raise_exception then if sqlerrm<>'shared_night_plan_cancelled' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',privacy_pid,'receiptID',gen_random_uuid(),'memberEpochID',privacy_epoch,'agreementID',privacy_agreement->>'agreementID','sourceID',gen_random_uuid(),'revision',100,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','actualStart',(d+time '21:35')::timestamptz,'terminalAt',(d+time '22:05')::timestamptz,'outcome','completed','windDownMinutes',30,'protectionEvidence','observed')); raise exception 'privacy-cancelled planless receipt accepted'; exception when raise_exception then if sqlerrm<>'shared_night_plan_cancelled' then raise; end if; end;
  if (select revision from private.night_flock_v4_parties where id=privacy_pid)<>archive_before or (select count(*) from private.night_flock_v4_shared_night_receipts where party_id=privacy_pid)<>1 then raise exception 'privacy receipt rejection churned archive or stored delayed replay'; end if;

  -- Schedule cancellation is revision-ordered and reversible; a privacy
  -- cancellation upgrades it exactly once and stays terminal.
  ordering_pid:=(public.night_flock_v4_command(privacy_host_id,jsonb_build_object('command','createParty','name','V2 cancellation ordering','timeZoneIdentifier','UTC'))->>'resolvedPartyID')::uuid;
  insert into private.night_flock_v4_memberships(party_id,user_id,role) values(ordering_pid,member_id,'member');
  ordering_agreement:=public.night_flock_v4_command(member_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',ordering_pid,'agreementVersion',2,'timeZoneIdentifier','UTC'));
  ordering_epoch:=(ordering_agreement->>'memberEpochID')::uuid;
  ordering_plan:=gen_random_uuid();
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',ordering_pid,'planID',ordering_plan,'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',3,'nightEndingDate',d+2,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '21:30')::timestamptz,'intendedBedtime',(d+1+time '22:00')::timestamptz,'intendedWakeTime',(d+2+time '07:00')::timestamptz,'morningQuietEnd',(d+2+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  select revision into archive_before from private.night_flock_v4_parties where id=ordering_pid;
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',ordering_pid,'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',2,'nightEndingDate',d+2,'timeZoneIdentifier','UTC','cancellationAuthority','schedule'))->>'staleRevision')::boolean,false)
     or (select revision from private.night_flock_v4_parties where id=ordering_pid)<>archive_before
     or exists(select 1 from private.night_flock_v4_shared_night_plan_tombstones where party_id=ordering_pid and member_epoch_id=ordering_epoch and night_ending_date=d+2)
  then raise exception 'delayed schedule cancellation hid an equal-or-newer plan'; end if;
  state:=public.night_flock_v4_state(member_id,'sharedNights',ordering_pid,null);
  if not exists(select 1 from jsonb_array_elements(state->'sharedNightPlans') value where (value->>'planID')::uuid=ordering_plan) then raise exception 'delayed schedule cancellation hid the visible plan'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',ordering_pid,'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',4,'nightEndingDate',d+2,'timeZoneIdentifier','UTC','cancellationAuthority','schedule'));
  if not exists(select 1 from private.night_flock_v4_shared_night_plan_tombstones where party_id=ordering_pid and member_epoch_id=ordering_epoch and night_ending_date=d+2 and revision=4 and cancellation_authority='schedule') then raise exception 'newer schedule cancellation was not stored'; end if;
  ordering_plan:=gen_random_uuid();
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',ordering_pid,'planID',ordering_plan,'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',5,'nightEndingDate',d+2,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '21:30')::timestamptz,'intendedBedtime',(d+1+time '22:00')::timestamptz,'intendedWakeTime',(d+2+time '07:00')::timestamptz,'morningQuietEnd',(d+2+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  if exists(select 1 from private.night_flock_v4_shared_night_plan_tombstones where party_id=ordering_pid and member_epoch_id=ordering_epoch and night_ending_date=d+2) then raise exception 'newer plan did not revive schedule cancellation'; end if;

  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',ordering_pid,'planID',gen_random_uuid(),'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',3,'nightEndingDate',d+3,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+2+time '21:30')::timestamptz,'intendedBedtime',(d+2+time '22:00')::timestamptz,'intendedWakeTime',(d+3+time '07:00')::timestamptz,'morningQuietEnd',(d+3+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',ordering_pid,'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',4,'nightEndingDate',d+3,'timeZoneIdentifier','UTC','cancellationAuthority','schedule'));
  select revision into archive_before from private.night_flock_v4_parties where id=ordering_pid;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',ordering_pid,'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',2,'nightEndingDate',d+3,'timeZoneIdentifier','UTC','cancellationAuthority','privacy'));
  if not exists(select 1 from private.night_flock_v4_shared_night_plan_tombstones where party_id=ordering_pid and member_epoch_id=ordering_epoch and night_ending_date=d+3 and revision=4 and cancellation_authority='privacy')
     or (select revision from private.night_flock_v4_parties where id=ordering_pid)<>archive_before+1
  then raise exception 'privacy cancellation did not upgrade schedule authority once'; end if;
  select revision into archive_before from private.night_flock_v4_parties where id=ordering_pid;
  if not coalesce((public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',ordering_pid,'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',2,'nightEndingDate',d+3,'timeZoneIdentifier','UTC','cancellationAuthority','privacy'))->>'staleRevision')::boolean,false)
     or (select revision from private.night_flock_v4_parties where id=ordering_pid)<>archive_before
  then raise exception 'repeated privacy cancellation churned archive'; end if;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',ordering_pid,'planID',gen_random_uuid(),'memberEpochID',ordering_epoch,'agreementID',ordering_agreement->>'agreementID','revision',5,'nightEndingDate',d+3,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+2+time '21:30')::timestamptz,'intendedBedtime',(d+2+time '22:00')::timestamptz,'intendedWakeTime',(d+3+time '07:00')::timestamptz,'morningQuietEnd',(d+3+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'privacy tombstone allowed later plan revival'; exception when raise_exception then if sqlerrm<>'shared_night_plan_cancelled' then raise; end if; end;

  -- A schedule edit cannot hide a plan after its frozen start, while an
  -- explicit privacy choice still may. Incoming backdated plan revisions are
  -- rejected even when the stored plan itself remains future/unfrozen.
  freeze_pid:=(public.night_flock_v4_command(privacy_host_id,jsonb_build_object('command','createParty','name','V2 frozen cancellation','timeZoneIdentifier','UTC'))->>'resolvedPartyID')::uuid;
  insert into private.night_flock_v4_memberships(party_id,user_id,role) values(freeze_pid,member_id,'member');
  freeze_agreement:=public.night_flock_v4_command(member_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',freeze_pid,'agreementVersion',2,'timeZoneIdentifier','UTC'));
  freeze_epoch:=(freeze_agreement->>'memberEpochID')::uuid;
  freeze_plan:=gen_random_uuid();
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',freeze_pid,'planID',freeze_plan,'memberEpochID',freeze_epoch,'agreementID',freeze_agreement->>'agreementID','revision',1,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+1+time '00:30')::timestamptz,'intendedBedtime',(d+1+time '01:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb));
  select revision into archive_before from private.night_flock_v4_parties where id=freeze_pid;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',freeze_pid,'planID',gen_random_uuid(),'memberEpochID',freeze_epoch,'agreementID',freeze_agreement->>'agreementID','revision',2,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','plannedWindDownStart',date_trunc('hour',now()),'intendedBedtime',date_trunc('hour',now())+interval '30 minutes','intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'backdated incoming revision superseded future plan'; exception when raise_exception then if sqlerrm<>'shared_night_plan_frozen' then raise; end if; end;
  if (select revision from private.night_flock_v4_parties where id=freeze_pid)<>archive_before or not exists(select 1 from private.night_flock_v4_shared_night_plans where id=freeze_plan and superseded_at is null) then raise exception 'backdated plan rejection churned archive or superseded future plan'; end if;
  update private.night_flock_v4_shared_night_plans set planned_wind_down_start=now()-interval '5 minutes' where id=freeze_plan;
  select revision into archive_before from private.night_flock_v4_parties where id=freeze_pid;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',freeze_pid,'memberEpochID',freeze_epoch,'agreementID',freeze_agreement->>'agreementID','revision',3,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','cancellationAuthority','schedule')); raise exception 'schedule cancellation hid frozen plan'; exception when raise_exception then if sqlerrm<>'shared_night_plan_frozen' then raise; end if; end;
  if (select revision from private.night_flock_v4_parties where id=freeze_pid)<>archive_before or exists(select 1 from private.night_flock_v4_shared_night_plan_tombstones where party_id=freeze_pid and member_epoch_id=freeze_epoch and night_ending_date=d+1) then raise exception 'frozen schedule cancellation churned archive or wrote tombstone'; end if;
  state:=public.night_flock_v4_state(member_id,'sharedNights',freeze_pid,null);
  if not exists(select 1 from jsonb_array_elements(state->'sharedNightPlans') value where (value->>'planID')::uuid=freeze_plan) then raise exception 'frozen schedule cancellation hid visible plan'; end if;
  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','cancelSharedNightPlan','partyID',freeze_pid,'memberEpochID',freeze_epoch,'agreementID',freeze_agreement->>'agreementID','revision',3,'nightEndingDate',d+1,'timeZoneIdentifier','UTC','cancellationAuthority','privacy'));
  if not exists(select 1 from private.night_flock_v4_shared_night_plan_tombstones where party_id=freeze_pid and member_epoch_id=freeze_epoch and night_ending_date=d+1 and cancellation_authority='privacy') then raise exception 'explicit privacy cancellation did not fence frozen plan'; end if;

  perform public.night_flock_v4_command(member_id,jsonb_build_object('command','deleteSharedHabitHistory','partyID',pid,'allSources',true));
  begin perform public.night_flock_v4_state(member_id,'sharedNights',pid,cursor); raise exception 'v2 deletion left cursor valid'; exception when raise_exception then if sqlerrm<>'stale_revision' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid,'planID',gen_random_uuid(),'memberEpochID',epoch,'agreementID',agreement->>'agreementID','revision',103,'nightEndingDate',d,'timeZoneIdentifier','UTC','plannedWindDownStart',(d+time '21:30')::timestamptz,'intendedBedtime',(d+time '22:00')::timestamptz,'intendedWakeTime',(d+1+time '07:00')::timestamptz,'morningQuietEnd',(d+1+time '07:30')::timestamptz,'beforeBedMinutes',30,'afterWakingMinutes',30,'eveningSuggestionIDs','[]'::jsonb,'morningSuggestionIDs','[]'::jsonb)); raise exception 'tombstoned v2 replay accepted'; exception when raise_exception then if sqlerrm<>'shared_history_deleted' then raise; end if; end;
  update auth.users set is_anonymous=false,raw_app_meta_data='{"provider":"email","providers":["email"]}'::jsonb where id=member_id;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','acceptSharedHabitsAgreement','partyID',pid,'agreementVersion',2,'timeZoneIdentifier','UTC')); raise exception 'unlinked v2 agreement accepted'; exception when raise_exception then if sqlerrm<>'Apple-linked account required' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightPlan','partyID',pid)); raise exception 'unlinked v2 plan accepted'; exception when raise_exception then if sqlerrm<>'Apple-linked account required' then raise; end if; end;
  begin perform public.night_flock_v4_command(member_id,jsonb_build_object('command','publishSharedNightReceipt','partyID',pid)); raise exception 'unlinked v2 receipt accepted'; exception when raise_exception then if sqlerrm<>'Apple-linked account required' then raise; end if; end;
end $$;

rollback;
